FROM python:3.14.0a1-slim

RUN mkdir /app
WORKDIR /app
ADD requirements.txt .
RUN pip install -r requirements.txt

RUN opentelemetry-bootstrap -a install

ADD *.py ./
CMD ["opentelemetry-instrument", "/app/client.py"]
