name: Run integration test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Update configuration
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ORG_NAME: ${{ secrets.ORG_NAME }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: ./tools/update-token.sh

    - name: Validate config is up-to-date
      run: ./tools/precommit.sh

    - name: Build containers
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
      run: docker-compose build

    - name: Run integration test
      run: docker-compose up --exit-code-from integration-test integration-test
