name: Run integration test

on:
  push:
    branches:
      - main
  pull_request:  

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

  validate:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate config is up-to-date
      run: ./tools/precommit.sh

  build:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [
          'go-opentracing-server', 'go-opentracing-client',
          'go-opentelemetry-server', 'go-opentelemetry-client',
          'go-launcher-server', 'go-launcher-client',
          'py-lstrace-client', 'py-lstrace-server',
          'py-collector-client', 'py-collector-server',
          'py-opentelemetry-client', 'py-opentelemetry-server',
          'py-launcher-client', 'py-launcher-server',
          'demo-client-otlp', 'demo-client-lstrace',
          'py-opentracing-client', 'py-opentracing-server',
          'js-lstrace-server', 'js-lstrace-client',
          'js-launcher-server', 'js-launcher-client',
          'js-ot-shim-server', 'js-ot-shim-client',
          'java-specialagent-server', 'java-specialagent-client',
          'java-otlp-client', 'java-otlp-server',
          'java-launcher-client', 'java-launcher-server',
          'java-opentracing-server', 'integration-test'
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - id: cache-docker
      uses: actions/cache@v1
      with:
        path: /tmp/docker-registry
        key: docker-registry-no-buildkit-${{ hashFiles('docker-compose.yml') }}

    - name: Run local docker registry
      run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000

    - name: Update configuration
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ORG_NAME: ${{ secrets.ORG_NAME }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: ./tools/update-token.sh

    - name: Build containers
      run: docker-compose build ${{ matrix.component }}

    - name: Push containers
      run: docker-compose push ${{ matrix.component }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - id: cache-docker
      uses: actions/cache@v1
      with:
        path: /tmp/docker-registry
        key: docker-registry-no-buildkit-${{ hashFiles('docker-compose.yml') }}

    - name: Run local docker registry
      run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000

    - name: Update configuration
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ORG_NAME: ${{ secrets.ORG_NAME }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: ./tools/update-token.sh

    - name: Run integration tests
      run: docker-compose pull && docker-compose up --no-build --exit-code-from integration-test integration-test
