name: Run docker-compose

# Runs examples every hour for 30 seconds
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Update configuration
      run: |
        cp example.env .env
        sed -i '' 's/<ACCESS TOKEN>/${TOKEN}/' .env
        cp example-collector-config.yaml ./collector/collector-config.yaml
        sed -i '' 's/<ACCESS TOKEN>/${TOKEN}/' ./collector/collector-config.yaml

    - name: Run docker-compose
      run: docker-compose up -d

    - name: Sleep 30s
      run:
        sleep 30

    - name: Run docker-compose
      run: docker-compose down
